name:                ref-extras
version:             0.2.0
github:              "ejconlon/ref-extras"
license:             BSD3
author:              "Eric Conlon"
maintainer:          "ejconlon@gmail.com"
copyright:           "(c) 2020 Eric Conlon"
category:            Data
synopsis:            Extra stuff for mutable references

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/ejconlon/ref-extras#readme>

dependencies:
- base >= 4.12 && < 5
- hashable >= 1.3 && < 2
- little-rio >= 0.2.1 && < 1
- microlens >= 0.4 && < 1
- stm >= 2.5 && < 3
- unliftio >= 0.2 && < 1
- unliftio-core >= 0.1 && < 1
- unordered-containers >= 0.2 && < 1

default-extensions:
- FlexibleInstances
- GADTs
- MultiParamTypeClasses
- Rank2Types

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-unused-top-binds

library:
  source-dirs: src
